services:
  - type: web
    name: fastapi-streamlit-app
    env: python
    region: oregon
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: 1
